# task name
name:
  "omniglot"

# random seed
seed:
  0

# how many training steps (each step trains a batch) in training stage
total_train_iter:
  100

# perform a validation after how many training steps
val_interval:
  10

# how many batchs in each validation stage
val_size:
  10
  
# how many batchs in test stage
test_size:
  100

# result file root
ckpt_path:
  "result_files"

# actually, it is the number of episode in each batch, for 5way-1shot-15query task, each episode has 5 * (1+15) = 80 images
batch_size:
  1

# number of way (class) per episode
N:
  5
  
# number of image per class in support set (shot)
K:
  1
  
# number of image per class in query set (query)
Q:
  15
